### ISSUE TITLE
Cannot build using Swift 3 on OS X from Xcode 8.2-beta

### ISSUE THREAD

**Issue by raphaeltraviss** [SwiftGL/OpenGL#1]
I am following the tutorial from the "Hello Window" example on swiftgl.org--it doesn't build on my Mac.  I've tried building with `swift build` and `swift build -Xcc -I/usr/local/include -Xlinker -L/usr/local/lib`, and I seem to get the same errors on both.

Output of `swift --version`:

```
Apple Swift version 3.0 (swiftlang-800.0.33.1 clang-800.0.31)
Target: x86_64-apple-macosx10.9
```

Attached error output: [errors.txt](https://github.com/SwiftGL/swiftgl.github.io/files/363165/errors.txt)

I also see errors for SGLMath and SGLImage.

**Comment by jkolb** [comment]
Work is being started to update to Swift 3. Not planning on working on Swift 4 support until it is fully released to avoid dealing with Swift bugs from changes during the Beta period.
